name: Pull Request

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Testing 3DS Package
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Verify WWDR cert is installed
        run: |
          security find-certificate -a -c "Apple Worldwide Developer Relations Certification Authority" /Library/Keychains/System.keychain
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest-stable'

      - name: Clean Derived Data
        run: rm -rf ~/Library/Developer/Xcode/DerivedData/*

      - name: Testing with ThreeDsTester app
        run: exec .github/scripts/integration-test.sh
        env:
          DEV_BT_API_KEY: ${{ secrets.DEV_BT_API_KEY }}
          DEV_PRIVATE_BT_API_KEY: ${{ secrets.DEV_PRIVATE_BT_API_KEY }}

  dependency-check-test:
    name: Dependency Check Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dependency Check
        run: |
          docker run -v "/home/runner/work/3ds-ios/3ds-ios":"/github/workspace" --workdir "/github/workspace" owasp/dependency-check-action:latest --enableExperimental --project "ThreeDS" --failOnCVSS 1 --scan "Package.swift" --out "/github/workspace/reports"

      - name: Upload Test results
        if: success() || failure()
        uses: actions/upload-artifact@master
        with:
           name: Dependency check report
           path: ${{github.workspace}}/reports
